name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploys
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Clean modcache
        run: go clean -modcache

      - name: Test scripts
        run: echo "It did run brow main"

      - name: Clean Go module cache
        run: rm -rf ~/go/pkg/mod

      - name: Build scripts
        run: chmod +x ./scripts/buildprod.sh && ./scripts/buildprod.sh
